Update references to simple agent to app in quickstart
8090-inc/xrx-core pull request #17
Opened 2024-09-27 15:50 UTC by arjun-krishna1

- Point to "Simple App" in sample applications instead of non-existent "Simple Agent"
https://github.com/8090-inc/xrx-core/issues/16

2024-09-27 15:59 UTC, arjun-krishna1 commented on docs/content/quickstart.md
> +xRx requires three external services: LLM, Text-to-Speech, and Speech-to-Text. Configure these services by copying the `env-example.txt` to a `.env` file and setting the environment variables inside
This was another thing that tripped me up for a second when setting this up.
There wasn't a .env or a .env.example file
But there are env-example.txt files with the right format
I've updated the instructions to make this explicit

2024-10-08 17:36 UTC, sabbyanandan requested changes
@arjun-krishna1: This is a good change; however, there are a few other references to "Simple Agent" in the quickstart; it would be nice to clean then up, also.

Example: https://github.com/8090-inc/xrx-core/blob/main/docs/content/quickstart.md#how-to-run-the-simple-agent-application

2024-10-08 17:36 UTC, sabbyanandan commented on docs/content/quickstart.md
> +xRx requires three external services: LLM, Text-to-Speech, and Speech-to-Text. Configure these services by copying the `env-example.txt` to a `.env` file and setting the environment variables inside
Good change; thanks for fixing it.

2024-10-10 22:53 UTC, arjun-krishna1 commented
Hi @sabbyanandan, thanks for the review!
I think I have actually updated all references to "Simple Agent" to `simple-app`
For example the section you pointed out on main is now renamed to "How to run simple app" on this branch
https://github.com/8090-inc/xrx-core/blob/6ca2826a9b87c6434a46be52b77fe5f567df9c23/docs/content/quickstart.md#how-to-run-simple-app

2024-10-10 23:05 UTC, sabbyanandan approved these changes
:shipit:

2024-10-10 23:05 UTC, sabbyanandan commented
Thanks, @arjun-krishna1!

2024-10-10 23:05 UTC, merged